/**
 * Migration Report Generator
 * Creates a markdown report from the analysis results
 */

import { AnalysisResult } from './analyzer';

export function generateReport(analysis: AnalysisResult): string {
    const lines: string[] = [];

    lines.push(`# MV3 Migration Report: ${analysis.extensionName}`);
    lines.push('');
    lines.push(`**Current Version:** Manifest V${analysis.manifestVersion}`);
    lines.push(`**Generated:** ${new Date().toISOString()}`);
    lines.push(`**Generator:** [mv3-migrate](https://github.com/theluckystrike/mv3-migrate) by Zovo`);
    lines.push('');

    // Summary
    lines.push('## Summary');
    lines.push('');
    lines.push(`| Severity | Count |`);
    lines.push(`|----------|-------|`);
    lines.push(`| 🔴 Critical | ${analysis.stats.critical} |`);
    lines.push(`| 🟡 Warning | ${analysis.stats.warning} |`);
    lines.push(`| 🔵 Info | ${analysis.stats.info} |`);
    lines.push(`| **Total** | **${analysis.stats.totalIssues}** |`);
    lines.push('');

    if (analysis.stats.totalIssues === 0) {
        lines.push('✅ No migration issues found! Your extension appears to be MV3 compatible.');
        return lines.join('\n');
    }

    // Critical issues
    const critical = analysis.issues.filter((i) => i.severity === 'critical');
    if (critical.length > 0) {
        lines.push('## 🔴 Critical Issues (Must Fix)');
        lines.push('');
        for (const issue of critical) {
            lines.push(`### ${issue.category}`);
            lines.push(`- **Issue:** ${issue.description}`);
            lines.push(`- **Action:** ${issue.action}`);
            if (issue.file) lines.push(`- **File:** \`${issue.file}\``);
            lines.push('');
        }
    }

    // Warnings
    const warnings = analysis.issues.filter((i) => i.severity === 'warning');
    if (warnings.length > 0) {
        lines.push('## 🟡 Warnings (Should Fix)');
        lines.push('');
        for (const issue of warnings) {
            lines.push(`### ${issue.category}`);
            lines.push(`- **Issue:** ${issue.description}`);
            lines.push(`- **Action:** ${issue.action}`);
            if (issue.file) lines.push(`- **File:** \`${issue.file}\``);
            lines.push('');
        }
    }

    // Info
    const info = analysis.issues.filter((i) => i.severity === 'info');
    if (info.length > 0) {
        lines.push('## 🔵 Info');
        lines.push('');
        for (const issue of info) {
            lines.push(`- ${issue.description} → ${issue.action}`);
        }
        lines.push('');
    }

    // Resources
    lines.push('## Resources');
    lines.push('');
    lines.push('- [Chrome MV3 Migration Guide](https://developer.chrome.com/docs/extensions/develop/migrate)');
    lines.push('- [MV3 Migration Checklist](https://developer.chrome.com/docs/extensions/develop/migrate/checklist)');
    lines.push('- [chrome-extension-starter-mv3](https://github.com/theluckystrike/chrome-extension-starter-mv3) — Production MV3 template');
    lines.push('');
    lines.push('---');
    lines.push('*Generated by [mv3-migrate](https://github.com/theluckystrike/mv3-migrate) — Built by [Zovo](https://zovo.one)*');

    return lines.join('\n');
}
